import datetime
from PyQt4 import QtCore,QtGui
from PyQt4.QtCore import QTimeLine
from PyQt4.QtGui import *
import sys


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1921, 1080))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.widget = QtGui.QWidget(self.page)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1920, 150))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(310, 10, 300, 140))
        self.label.setStyleSheet(_fromUtf8("background-color: rgb(169, 166, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(610, 10, 225, 140))
        self.label_2.setStyleSheet(_fromUtf8("background-color: rgb(169, 166, 255);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(845, 10, 310, 140))
        self.label_3.setStyleSheet(_fromUtf8("background-color: rgb(15, 255, 95);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(1155, 10, 225, 140))
        self.label_4.setStyleSheet(_fromUtf8("background-color: rgb(15, 255, 95);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(1390, 10, 240, 140))
        self.label_5.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(160, 10, 140, 140))
        self.label_6.setStyleSheet(_fromUtf8("background-color: rgba(255,145,27,150);"))
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(1630, 10, 50, 140))
        self.label_7.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 140, 140))
        self.label_9.setStyleSheet(_fromUtf8(""))
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Sewing.png")))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(1680, 40, 230, 40))
        self.label_8.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(1680, 80, 230, 40))
        self.label_10.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.frame = QtGui.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(1620, 10, 290, 140))
        self.frame.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.frame_2 = QtGui.QFrame(self.page)
        self.frame_2.setGeometry(QtCore.QRect(0, 150, 1390, 930))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setMargin(9)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.page)
        self.frame_3.setGeometry(QtCore.QRect(1390, 150, 520, 930))
        self.frame_3.setStyleSheet(_fromUtf8("background-color: rgb(225, 148, 255);"))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_11 = QtGui.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(50, 30, 221, 41))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(50, 190, 221, 41))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(40, 550, 221, 41))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.frame_4 = QtGui.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(170, 70, 2, 75))
        self.frame_4.setStyleSheet(_fromUtf8("background-color: rgb(118, 118, 118);"))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.frame_5 = QtGui.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(170, 230, 2, 275))
        self.frame_5.setStyleSheet(_fromUtf8("background-color: rgb(118, 118, 118);"))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.frame_6 = QtGui.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(170, 600, 2, 210))
        self.frame_6.setStyleSheet(_fromUtf8("background-color: rgb(118, 118, 118);"))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.label_16 = QtGui.QLabel(self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(190, 450, 101, 31))
        self.label_16.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.frame_3)
        self.label_17.setGeometry(QtCore.QRect(190, 250, 111, 31))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.frame_3)
        self.label_18.setGeometry(QtCore.QRect(190, 320, 101, 31))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.frame_3)
        self.label_19.setGeometry(QtCore.QRect(190, 390, 101, 31))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(190, 620, 111, 31))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.frame_3)
        self.label_21.setGeometry(QtCore.QRect(190, 690, 101, 31))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.frame_3)
        self.label_22.setGeometry(QtCore.QRect(190, 760, 101, 31))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.frame_3)
        self.label_23.setGeometry(QtCore.QRect(330, 450, 101, 31))
        self.label_23.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.frame_3)
        self.label_24.setGeometry(QtCore.QRect(330, 250, 101, 31))
        self.label_24.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.frame_3)
        self.label_25.setGeometry(QtCore.QRect(330, 320, 101, 31))
        self.label_25.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(330, 390, 101, 31))
        self.label_26.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.frame_3)
        self.label_27.setGeometry(QtCore.QRect(330, 620, 101, 31))
        self.label_27.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.frame_3)
        self.label_28.setGeometry(QtCore.QRect(330, 690, 101, 31))
        self.label_28.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.frame_3)
        self.label_29.setGeometry(QtCore.QRect(330, 760, 101, 31))
        self.label_29.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.frame_3)
        self.label_30.setGeometry(QtCore.QRect(190, 90, 101, 31))
        self.label_30.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.frame_3)
        self.label_31.setGeometry(QtCore.QRect(330, 90, 101, 31))
        self.label_31.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.widget_2 = QtGui.QWidget(self.page_2)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 1931, 150))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.label_51 = QtGui.QLabel(self.widget_2)
        self.label_51.setGeometry(QtCore.QRect(310, 10, 300, 140))
        self.label_51.setStyleSheet(_fromUtf8("background-color: rgb(169, 166, 255);"))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.label_52 = QtGui.QLabel(self.widget_2)
        self.label_52.setGeometry(QtCore.QRect(610, 10, 225, 140))
        self.label_52.setStyleSheet(_fromUtf8("background-color: rgb(169, 166, 255);"))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.label_53 = QtGui.QLabel(self.widget_2)
        self.label_53.setGeometry(QtCore.QRect(845, 10, 310, 140))
        self.label_53.setStyleSheet(_fromUtf8("background-color: rgb(15, 255, 95);"))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.label_54 = QtGui.QLabel(self.widget_2)
        self.label_54.setGeometry(QtCore.QRect(1155, 10, 225, 140))
        self.label_54.setStyleSheet(_fromUtf8("background-color: rgb(15, 255, 95);"))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.label_55 = QtGui.QLabel(self.widget_2)
        self.label_55.setGeometry(QtCore.QRect(1390, 10, 240, 140))
        self.label_55.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_56 = QtGui.QLabel(self.widget_2)
        self.label_56.setGeometry(QtCore.QRect(160, 10, 140, 140))
        self.label_56.setStyleSheet(_fromUtf8("background-color: rgb(255, 185, 237);"))
        self.label_56.setScaledContents(False)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.label_57 = QtGui.QLabel(self.widget_2)
        self.label_57.setGeometry(QtCore.QRect(1630, 10, 50, 140))
        self.label_57.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.label_58 = QtGui.QLabel(self.widget_2)
        self.label_58.setGeometry(QtCore.QRect(10, 10, 140, 140))
        self.label_58.setStyleSheet(_fromUtf8(""))
        self.label_58.setText(_fromUtf8(""))
        self.label_58.setPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Sewing.png")))
        self.label_58.setScaledContents(True)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.label_59 = QtGui.QLabel(self.widget_2)
        self.label_59.setGeometry(QtCore.QRect(1680, 40, 230, 40))
        self.label_59.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.label_60 = QtGui.QLabel(self.widget_2)
        self.label_60.setGeometry(QtCore.QRect(1680, 80, 230, 40))
        self.label_60.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.frame_8 = QtGui.QFrame(self.widget_2)
        self.frame_8.setGeometry(QtCore.QRect(1620, 10, 290, 140))
        self.frame_8.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.frame_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.frame_8.raise_()
        self.label_51.raise_()
        self.label_52.raise_()
        self.label_53.raise_()
        self.label_54.raise_()
        self.label_55.raise_()
        self.label_56.raise_()
        self.label_57.raise_()
        self.label_58.raise_()
        self.label_59.raise_()
        self.label_60.raise_()
        self.frame_9 = QtGui.QFrame(self.page_2)
        self.frame_9.setGeometry(QtCore.QRect(0, 150, 1390, 930))
        self.frame_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_9)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setMargin(9)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.frame_7 = QtGui.QFrame(self.page_2)
        self.frame_7.setGeometry(QtCore.QRect(1390, 150, 520, 930))
        self.frame_7.setStyleSheet(_fromUtf8("background-color: rgb(225, 148, 255);"))
        self.frame_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.label_14 = QtGui.QLabel(self.frame_7)
        self.label_14.setGeometry(QtCore.QRect(50, 30, 221, 41))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.frame_7)
        self.label_15.setGeometry(QtCore.QRect(50, 190, 221, 41))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_32 = QtGui.QLabel(self.frame_7)
        self.label_32.setGeometry(QtCore.QRect(40, 550, 221, 41))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.frame_10 = QtGui.QFrame(self.frame_7)
        self.frame_10.setGeometry(QtCore.QRect(170, 70, 2, 75))
        self.frame_10.setStyleSheet(_fromUtf8("background-color: rgb(118, 118, 118);"))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.frame_17 = QtGui.QFrame(self.frame_7)
        self.frame_17.setGeometry(QtCore.QRect(170, 230, 2, 275))
        self.frame_17.setStyleSheet(_fromUtf8("background-color: rgb(118, 118, 118);"))
        self.frame_17.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_17.setObjectName(_fromUtf8("frame_17"))
        self.frame_18 = QtGui.QFrame(self.frame_7)
        self.frame_18.setGeometry(QtCore.QRect(170, 600, 2, 210))
        self.frame_18.setStyleSheet(_fromUtf8("background-color: rgb(118, 118, 118);"))
        self.frame_18.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_18.setObjectName(_fromUtf8("frame_18"))
        self.label_33 = QtGui.QLabel(self.frame_7)
        self.label_33.setGeometry(QtCore.QRect(190, 450, 101, 31))
        self.label_33.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.frame_7)
        self.label_34.setGeometry(QtCore.QRect(190, 250, 111, 31))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.frame_7)
        self.label_35.setGeometry(QtCore.QRect(190, 320, 101, 31))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.frame_7)
        self.label_36.setGeometry(QtCore.QRect(190, 390, 101, 31))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.frame_7)
        self.label_37.setGeometry(QtCore.QRect(190, 620, 111, 31))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.frame_7)
        self.label_38.setGeometry(QtCore.QRect(190, 690, 101, 31))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.frame_7)
        self.label_39.setGeometry(QtCore.QRect(190, 760, 101, 31))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.frame_7)
        self.label_40.setGeometry(QtCore.QRect(330, 450, 101, 31))
        self.label_40.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.frame_7)
        self.label_41.setGeometry(QtCore.QRect(330, 250, 101, 31))
        self.label_41.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_42 = QtGui.QLabel(self.frame_7)
        self.label_42.setGeometry(QtCore.QRect(330, 320, 101, 31))
        self.label_42.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_43 = QtGui.QLabel(self.frame_7)
        self.label_43.setGeometry(QtCore.QRect(330, 390, 101, 31))
        self.label_43.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_44 = QtGui.QLabel(self.frame_7)
        self.label_44.setGeometry(QtCore.QRect(330, 620, 101, 31))
        self.label_44.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.frame_7)
        self.label_45.setGeometry(QtCore.QRect(330, 690, 101, 31))
        self.label_45.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_46 = QtGui.QLabel(self.frame_7)
        self.label_46.setGeometry(QtCore.QRect(330, 760, 101, 31))
        self.label_46.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.label_47 = QtGui.QLabel(self.frame_7)
        self.label_47.setGeometry(QtCore.QRect(190, 90, 101, 31))
        self.label_47.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.label_48 = QtGui.QLabel(self.frame_7)
        self.label_48.setGeometry(QtCore.QRect(330, 90, 101, 31))
        self.label_48.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.widget_3 = QtGui.QWidget(self.page_3)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 1931, 150))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.label_61 = QtGui.QLabel(self.widget_3)
        self.label_61.setGeometry(QtCore.QRect(310, 10, 300, 140))
        self.label_61.setStyleSheet(_fromUtf8("background-color: rgb(169, 166, 255);"))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.label_62 = QtGui.QLabel(self.widget_3)
        self.label_62.setGeometry(QtCore.QRect(610, 10, 225, 140))
        self.label_62.setStyleSheet(_fromUtf8("background-color: rgb(169, 166, 255);"))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.label_63 = QtGui.QLabel(self.widget_3)
        self.label_63.setGeometry(QtCore.QRect(845, 10, 310, 140))
        self.label_63.setStyleSheet(_fromUtf8("background-color: rgb(15, 255, 95);"))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_64 = QtGui.QLabel(self.widget_3)
        self.label_64.setGeometry(QtCore.QRect(1155, 10, 225, 140))
        self.label_64.setStyleSheet(_fromUtf8("background-color: rgb(15, 255, 95);"))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.label_65 = QtGui.QLabel(self.widget_3)
        self.label_65.setGeometry(QtCore.QRect(1390, 10, 240, 140))
        self.label_65.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.label_66 = QtGui.QLabel(self.widget_3)
        self.label_66.setGeometry(QtCore.QRect(160, 10, 140, 140))
        self.label_66.setStyleSheet(_fromUtf8("background-color: rgba(151,224,120,200);"))
        self.label_66.setScaledContents(False)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.label_67 = QtGui.QLabel(self.widget_3)
        self.label_67.setGeometry(QtCore.QRect(1630, 10, 50, 140))
        self.label_67.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.label_68 = QtGui.QLabel(self.widget_3)
        self.label_68.setGeometry(QtCore.QRect(10, 10, 140, 140))
        self.label_68.setStyleSheet(_fromUtf8(""))
        self.label_68.setText(_fromUtf8(""))
        self.label_68.setPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Sewing.png")))
        self.label_68.setScaledContents(True)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.label_69 = QtGui.QLabel(self.widget_3)
        self.label_69.setGeometry(QtCore.QRect(1680, 40, 230, 40))
        self.label_69.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.label_70 = QtGui.QLabel(self.widget_3)
        self.label_70.setGeometry(QtCore.QRect(1680, 80, 230, 40))
        self.label_70.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.frame_11 = QtGui.QFrame(self.widget_3)
        self.frame_11.setGeometry(QtCore.QRect(1620, 10, 290, 140))
        self.frame_11.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.frame_11.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.frame_11.raise_()
        self.label_61.raise_()
        self.label_62.raise_()
        self.label_63.raise_()
        self.label_64.raise_()
        self.label_65.raise_()
        self.label_66.raise_()
        self.label_67.raise_()
        self.label_68.raise_()
        self.label_69.raise_()
        self.label_70.raise_()
        self.frame_12 = QtGui.QFrame(self.page_3)
        self.frame_12.setGeometry(QtCore.QRect(0, 150, 1390, 930))
        self.frame_12.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_12)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setMargin(9)
        self.gridLayout_6.setHorizontalSpacing(6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.frame_13 = QtGui.QFrame(self.page_3)
        self.frame_13.setGeometry(QtCore.QRect(1390, 150, 520, 930))
        self.frame_13.setStyleSheet(_fromUtf8("background-color: rgb(225, 148, 255);"))
        self.frame_13.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.label_49 = QtGui.QLabel(self.frame_13)
        self.label_49.setGeometry(QtCore.QRect(50, 30, 221, 41))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.label_50 = QtGui.QLabel(self.frame_13)
        self.label_50.setGeometry(QtCore.QRect(50, 190, 221, 41))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.label_81 = QtGui.QLabel(self.frame_13)
        self.label_81.setGeometry(QtCore.QRect(40, 550, 221, 41))
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.frame_19 = QtGui.QFrame(self.frame_13)
        self.frame_19.setGeometry(QtCore.QRect(170, 70, 2, 75))
        self.frame_19.setStyleSheet(_fromUtf8("background-color: rgb(118, 118, 118);"))
        self.frame_19.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_19.setObjectName(_fromUtf8("frame_19"))
        self.frame_20 = QtGui.QFrame(self.frame_13)
        self.frame_20.setGeometry(QtCore.QRect(170, 230, 2, 275))
        self.frame_20.setStyleSheet(_fromUtf8("background-color: rgb(118, 118, 118);"))
        self.frame_20.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_20.setObjectName(_fromUtf8("frame_20"))
        self.frame_21 = QtGui.QFrame(self.frame_13)
        self.frame_21.setGeometry(QtCore.QRect(170, 600, 2, 210))
        self.frame_21.setStyleSheet(_fromUtf8("background-color: rgb(118, 118, 118);"))
        self.frame_21.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_21.setObjectName(_fromUtf8("frame_21"))
        self.label_82 = QtGui.QLabel(self.frame_13)
        self.label_82.setGeometry(QtCore.QRect(190, 450, 101, 31))
        self.label_82.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.label_83 = QtGui.QLabel(self.frame_13)
        self.label_83.setGeometry(QtCore.QRect(190, 250, 111, 31))
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.label_84 = QtGui.QLabel(self.frame_13)
        self.label_84.setGeometry(QtCore.QRect(190, 320, 101, 31))
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.label_85 = QtGui.QLabel(self.frame_13)
        self.label_85.setGeometry(QtCore.QRect(190, 390, 101, 31))
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.label_86 = QtGui.QLabel(self.frame_13)
        self.label_86.setGeometry(QtCore.QRect(190, 620, 111, 31))
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.label_87 = QtGui.QLabel(self.frame_13)
        self.label_87.setGeometry(QtCore.QRect(190, 690, 101, 31))
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.label_88 = QtGui.QLabel(self.frame_13)
        self.label_88.setGeometry(QtCore.QRect(190, 760, 101, 31))
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.label_89 = QtGui.QLabel(self.frame_13)
        self.label_89.setGeometry(QtCore.QRect(330, 450, 101, 31))
        self.label_89.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.label_90 = QtGui.QLabel(self.frame_13)
        self.label_90.setGeometry(QtCore.QRect(330, 250, 101, 31))
        self.label_90.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.label_91 = QtGui.QLabel(self.frame_13)
        self.label_91.setGeometry(QtCore.QRect(330, 320, 101, 31))
        self.label_91.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.label_92 = QtGui.QLabel(self.frame_13)
        self.label_92.setGeometry(QtCore.QRect(330, 390, 101, 31))
        self.label_92.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.label_93 = QtGui.QLabel(self.frame_13)
        self.label_93.setGeometry(QtCore.QRect(330, 620, 101, 31))
        self.label_93.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.label_94 = QtGui.QLabel(self.frame_13)
        self.label_94.setGeometry(QtCore.QRect(330, 690, 101, 31))
        self.label_94.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.label_95 = QtGui.QLabel(self.frame_13)
        self.label_95.setGeometry(QtCore.QRect(330, 760, 101, 31))
        self.label_95.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.label_96 = QtGui.QLabel(self.frame_13)
        self.label_96.setGeometry(QtCore.QRect(190, 90, 101, 31))
        self.label_96.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.label_97 = QtGui.QLabel(self.frame_13)
        self.label_97.setGeometry(QtCore.QRect(330, 90, 101, 31))
        self.label_97.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.widget_4 = QtGui.QWidget(self.page_4)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 1931, 150))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.label_71 = QtGui.QLabel(self.widget_4)
        self.label_71.setGeometry(QtCore.QRect(310, 10, 300, 140))
        self.label_71.setStyleSheet(_fromUtf8("background-color: rgb(169, 166, 255);"))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.label_72 = QtGui.QLabel(self.widget_4)
        self.label_72.setGeometry(QtCore.QRect(610, 10, 225, 140))
        self.label_72.setStyleSheet(_fromUtf8("background-color: rgb(169, 166, 255);"))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.label_73 = QtGui.QLabel(self.widget_4)
        self.label_73.setGeometry(QtCore.QRect(845, 10, 310, 140))
        self.label_73.setStyleSheet(_fromUtf8("background-color: rgb(15, 255, 95);"))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.label_74 = QtGui.QLabel(self.widget_4)
        self.label_74.setGeometry(QtCore.QRect(1155, 10, 225, 140))
        self.label_74.setStyleSheet(_fromUtf8("background-color: rgb(15, 255, 95);"))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.label_75 = QtGui.QLabel(self.widget_4)
        self.label_75.setGeometry(QtCore.QRect(1390, 10, 240, 140))
        self.label_75.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.label_76 = QtGui.QLabel(self.widget_4)
        self.label_76.setGeometry(QtCore.QRect(160, 10, 140, 140))
        self.label_76.setStyleSheet(_fromUtf8("background-color: rgba(243,80,80,150);"))
        self.label_76.setScaledContents(False)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.label_77 = QtGui.QLabel(self.widget_4)
        self.label_77.setGeometry(QtCore.QRect(1630, 10, 50, 140))
        self.label_77.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.label_78 = QtGui.QLabel(self.widget_4)
        self.label_78.setGeometry(QtCore.QRect(10, 10, 140, 140))
        self.label_78.setStyleSheet(_fromUtf8(""))
        self.label_78.setText(_fromUtf8(""))
        self.label_78.setPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Sewing.png")))
        self.label_78.setScaledContents(True)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.label_79 = QtGui.QLabel(self.widget_4)
        self.label_79.setGeometry(QtCore.QRect(1680, 40, 230, 40))
        self.label_79.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.label_80 = QtGui.QLabel(self.widget_4)
        self.label_80.setGeometry(QtCore.QRect(1680, 80, 230, 40))
        self.label_80.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.frame_14 = QtGui.QFrame(self.widget_4)
        self.frame_14.setGeometry(QtCore.QRect(1620, 10, 290, 140))
        self.frame_14.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 255);"))
        self.frame_14.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.frame_14.raise_()
        self.label_71.raise_()
        self.label_72.raise_()
        self.label_73.raise_()
        self.label_74.raise_()
        self.label_75.raise_()
        self.label_76.raise_()
        self.label_77.raise_()
        self.label_78.raise_()
        self.label_79.raise_()
        self.label_80.raise_()
        self.frame_15 = QtGui.QFrame(self.page_4)
        self.frame_15.setGeometry(QtCore.QRect(0, 150, 1390, 930))
        self.frame_15.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_15)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setMargin(9)
        self.gridLayout_8.setHorizontalSpacing(6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.frame_16 = QtGui.QFrame(self.page_4)
        self.frame_16.setGeometry(QtCore.QRect(1390, 150, 520, 930))
        self.frame_16.setStyleSheet(_fromUtf8("background-color: rgb(225, 148, 255);"))
        self.frame_16.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_16.setObjectName(_fromUtf8("frame_16"))
        self.label_98 = QtGui.QLabel(self.frame_16)
        self.label_98.setGeometry(QtCore.QRect(50, 30, 221, 41))
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.label_99 = QtGui.QLabel(self.frame_16)
        self.label_99.setGeometry(QtCore.QRect(50, 190, 221, 41))
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.label_100 = QtGui.QLabel(self.frame_16)
        self.label_100.setGeometry(QtCore.QRect(40, 550, 221, 41))
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.frame_22 = QtGui.QFrame(self.frame_16)
        self.frame_22.setGeometry(QtCore.QRect(170, 70, 2, 75))
        self.frame_22.setStyleSheet(_fromUtf8("background-color: rgb(118, 118, 118);"))
        self.frame_22.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_22.setObjectName(_fromUtf8("frame_22"))
        self.frame_23 = QtGui.QFrame(self.frame_16)
        self.frame_23.setGeometry(QtCore.QRect(170, 230, 2, 275))
        self.frame_23.setStyleSheet(_fromUtf8("background-color: rgb(118, 118, 118);"))
        self.frame_23.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_23.setObjectName(_fromUtf8("frame_23"))
        self.frame_24 = QtGui.QFrame(self.frame_16)
        self.frame_24.setGeometry(QtCore.QRect(170, 600, 2, 210))
        self.frame_24.setStyleSheet(_fromUtf8("background-color: rgb(118, 118, 118);"))
        self.frame_24.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_24.setObjectName(_fromUtf8("frame_24"))
        self.label_101 = QtGui.QLabel(self.frame_16)
        self.label_101.setGeometry(QtCore.QRect(190, 450, 101, 31))
        self.label_101.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.label_102 = QtGui.QLabel(self.frame_16)
        self.label_102.setGeometry(QtCore.QRect(190, 250, 111, 31))
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.label_103 = QtGui.QLabel(self.frame_16)
        self.label_103.setGeometry(QtCore.QRect(190, 320, 101, 31))
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.label_104 = QtGui.QLabel(self.frame_16)
        self.label_104.setGeometry(QtCore.QRect(190, 390, 101, 31))
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.label_105 = QtGui.QLabel(self.frame_16)
        self.label_105.setGeometry(QtCore.QRect(190, 620, 111, 31))
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.label_106 = QtGui.QLabel(self.frame_16)
        self.label_106.setGeometry(QtCore.QRect(190, 690, 101, 31))
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.label_107 = QtGui.QLabel(self.frame_16)
        self.label_107.setGeometry(QtCore.QRect(190, 760, 101, 31))
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.label_108 = QtGui.QLabel(self.frame_16)
        self.label_108.setGeometry(QtCore.QRect(330, 450, 101, 31))
        self.label_108.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.label_109 = QtGui.QLabel(self.frame_16)
        self.label_109.setGeometry(QtCore.QRect(330, 250, 101, 31))
        self.label_109.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.label_110 = QtGui.QLabel(self.frame_16)
        self.label_110.setGeometry(QtCore.QRect(330, 320, 101, 31))
        self.label_110.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.label_111 = QtGui.QLabel(self.frame_16)
        self.label_111.setGeometry(QtCore.QRect(330, 390, 101, 31))
        self.label_111.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.label_112 = QtGui.QLabel(self.frame_16)
        self.label_112.setGeometry(QtCore.QRect(330, 620, 101, 31))
        self.label_112.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_112.setObjectName(_fromUtf8("label_112"))
        self.label_113 = QtGui.QLabel(self.frame_16)
        self.label_113.setGeometry(QtCore.QRect(330, 690, 101, 31))
        self.label_113.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_113.setObjectName(_fromUtf8("label_113"))
        self.label_114 = QtGui.QLabel(self.frame_16)
        self.label_114.setGeometry(QtCore.QRect(330, 760, 101, 31))
        self.label_114.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_114.setObjectName(_fromUtf8("label_114"))
        self.label_115 = QtGui.QLabel(self.frame_16)
        self.label_115.setGeometry(QtCore.QRect(190, 90, 101, 31))
        self.label_115.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_115.setObjectName(_fromUtf8("label_115"))
        self.label_116 = QtGui.QLabel(self.frame_16)
        self.label_116.setGeometry(QtCore.QRect(330, 90, 101, 31))
        self.label_116.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.label_116.setObjectName(_fromUtf8("label_116"))
        self.stackedWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.StackWidTimer = QtCore.QTimer()
        self.StackWidTimer.timeout.connect(self.stackchange)
        self.StackWidTimer.start(10000)

        self.StackWidTimer1 = QtCore.QTimer()
        self.StackWidTimer1.timeout.connect(self.graph_draw)
        self.StackWidTimer1.start(1000)

        self.DateTimeTimer = QtCore.QTimer()
        self.DateTimeTimer.timeout.connect(self.update_time)
        self.DateTimeTimer.start(900)



    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "DSI - SP Production Monitoring System", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">Target</span></p></body></html>", None))
        # self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">1001</span></p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">Actual</span></p></body></html>", None))
        # self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">951</span></p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:48pt; color:#ffffff;\">12:00</span></p></body></html>", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt; font-weight:600; color:#ffffff;\">A</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#ffffff;\">PM</span></p></body></html>", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">Wednesday</span></p></body></html>", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">September</span></p></body></html>", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffffff;\">Hourly</span></p></body></html>", None))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffffff;\">Daily</span></p></body></html>", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffffff;\">Monthly</span></p></body></html>", None))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Loss</span></p></body></html>", None))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Target</span></p></body></html>", None))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Actual</span></p></body></html>", None))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Required</span></p></body></html>", None))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Target</span></p></body></html>", None))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Actual</span></p></body></html>", None))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Required</span></p></body></html>", None))
        # self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">051</span></p></body></html>", None))
        # self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">10001</span></p></body></html>", None))
        # self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">9501</span></p></body></html>", None))
        # self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">501</span></p></body></html>", None))
        # self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">30001</span></p></body></html>", None))
        # self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">25001</span></p></body></html>", None))
        # self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">5001</span></p></body></html>", None))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Loss</span></p></body></html>", None))
        # self.label_31.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">2051</span></p></body></html>", None))
        self.label_51.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">Target</span></p></body></html>", None))
        self.label_52.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">1102</span></p></body></html>", None))
        self.label_53.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">Actual</span></p></body></html>", None))
        self.label_54.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">972</span></p></body></html>", None))
        self.label_55.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:48pt; color:#ffffff;\">12:00</span></p></body></html>", None))
        self.label_56.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt; font-weight:600; color:#ffffff;\">B</span></p></body></html>", None))
        self.label_57.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#ffffff;\">PM</span></p></body></html>", None))
        self.label_59.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">Wednesday</span></p></body></html>", None))
        self.label_60.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">September</span></p></body></html>", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffffff;\">Hourly</span></p></body></html>", None))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffffff;\">Daily</span></p></body></html>", None))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffffff;\">Monthly</span></p></body></html>", None))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Loss</span></p></body></html>", None))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Target</span></p></body></html>", None))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Actual</span></p></body></html>", None))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Required</span></p></body></html>", None))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Target</span></p></body></html>", None))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Actual</span></p></body></html>", None))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Required</span></p></body></html>", None))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">052</span></p></body></html>", None))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">100002</span></p></body></html>", None))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">95002</span></p></body></html>", None))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">5002</span></p></body></html>", None))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">300002</span></p></body></html>", None))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">250002</span></p></body></html>", None))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">50002</span></p></body></html>", None))
        self.label_47.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Loss</span></p></body></html>", None))
        # self.label_48.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">2052</span></p></body></html>", None))
        self.label_61.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">Target</span></p></body></html>", None))
        self.label_62.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">1153</span></p></body></html>", None))
        self.label_63.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">Actual</span></p></body></html>", None))
        self.label_64.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">1003</span></p></body></html>", None))
        self.label_65.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:48pt; color:#ffffff;\">12:00</span></p></body></html>", None))
        self.label_66.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt; font-weight:600; color:#ffffff;\">C</span></p></body></html>", None))
        self.label_67.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#ffffff;\">PM</span></p></body></html>", None))
        self.label_69.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">Wednesday</span></p></body></html>", None))
        self.label_70.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">September</span></p></body></html>", None))
        self.label_49.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffffff;\">Hourly</span></p></body></html>", None))
        self.label_50.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffffff;\">Daily</span></p></body></html>", None))
        self.label_81.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffffff;\">Monthly</span></p></body></html>", None))
        self.label_82.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Loss</span></p></body></html>", None))
        self.label_83.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Target</span></p></body></html>", None))
        self.label_84.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Actual</span></p></body></html>", None))
        self.label_85.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Required</span></p></body></html>", None))
        self.label_86.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Target</span></p></body></html>", None))
        self.label_87.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Actual</span></p></body></html>", None))
        self.label_88.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Required</span></p></body></html>", None))
        self.label_89.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">053</span></p></body></html>", None))
        self.label_90.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">100003</span></p></body></html>", None))
        self.label_91.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">95003</span></p></body></html>", None))
        self.label_92.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">5003</span></p></body></html>", None))
        self.label_93.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">300003</span></p></body></html>", None))
        self.label_94.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">250003</span></p></body></html>", None))
        self.label_95.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">50003</span></p></body></html>", None))
        self.label_96.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Loss</span></p></body></html>", None))
        # self.label_97.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">2053</span></p></body></html>", None))
        self.label_71.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">Target</span></p></body></html>", None))
        self.label_72.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">1154</span></p></body></html>", None))
        self.label_73.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">Actual</span></p></body></html>", None))
        self.label_74.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:72pt; color:#ffffff;\">1004</span></p></body></html>", None))
        self.label_75.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:48pt; color:#ffffff;\">12:00</span></p></body></html>", None))
        self.label_76.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt; font-weight:600; color:#ffffff;\">D</span></p></body></html>", None))
        self.label_77.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#ffffff;\">PM</span></p></body></html>", None))
        self.label_79.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">Wednesday</span></p></body></html>", None))
        self.label_80.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">September</span></p></body></html>", None))
        self.label_98.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffffff;\">Hourly</span></p></body></html>", None))
        self.label_99.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffffff;\">Daily</span></p></body></html>", None))
        self.label_100.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffffff;\">Monthly</span></p></body></html>", None))
        self.label_101.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Loss</span></p></body></html>", None))
        self.label_102.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Target</span></p></body></html>", None))
        self.label_103.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Actual</span></p></body></html>", None))
        self.label_104.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Required</span></p></body></html>", None))
        self.label_105.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Target</span></p></body></html>", None))
        self.label_106.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Actual</span></p></body></html>", None))
        self.label_107.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Required</span></p></body></html>", None))
        self.label_108.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">054</span></p></body></html>", None))
        self.label_109.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">100004</span></p></body></html>", None))
        self.label_110.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">95004</span></p></body></html>", None))
        self.label_111.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">5004</span></p></body></html>", None))
        self.label_112.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">300004</span></p></body></html>", None))
        self.label_113.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">250004</span></p></body></html>", None))
        self.label_114.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">50004</span></p></body></html>", None))
        self.label_115.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Loss</span></p></body></html>", None))
        # self.label_116.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">2054</span></p></body></html>", None))

    def update_time(self):
        Mytime = str(datetime.datetime.now().strftime('%I:%M'))
        MyDay = str(datetime.datetime.now().strftime('%A'))
        MyMonth = str(datetime.datetime.now().strftime('%B'))
        MyAm_Pm = str(datetime.datetime.now().strftime('%p'))
        self.label_5.setText(_translate("MainWindow",
                                      "<html><head/><body><p align=\"right\"><span style=\" font-size:48pt; color:#ffffff;\">" + Mytime + "</span></p></body></html>",
                                      None))
        self.label_55.setText(_translate("MainWindow",
                                       "<html><head/><body><p align=\"right\"><span style=\" font-size:48pt; color:#ffffff;\">" + Mytime + "</span></p></body></html>",
                                       None))
        self.label_65.setText(_translate("MainWindow",
                                       "<html><head/><body><p align=\"right\"><span style=\" font-size:48pt; color:#ffffff;\">" + Mytime + "</span></p></body></html>",
                                       None))
        self.label_75.setText(_translate("MainWindow",
                                       "<html><head/><body><p align=\"right\"><span style=\" font-size:48pt; color:#ffffff;\">" + Mytime + "</span></p></body></html>",
                                       None))
        self.label_8.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">" + MyDay + "</span></p></body></html>",
                                      None))
        self.label_59.setText(_translate("MainWindow",
                                       "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">" + MyDay + "</span></p></body></html>",
                                       None))
        self.label_69.setText(_translate("MainWindow",
                                       "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">" + MyDay + "</span></p></body></html>",
                                       None))
        self.label_79.setText(_translate("MainWindow",
                                       "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">" + MyDay + "</span></p></body></html>",
                                       None))
        self.label_10.setText(_translate("MainWindow",
                                       "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">" + MyMonth + "</span></p></body></html>",
                                       None))
        self.label_60.setText(_translate("MainWindow",
                                       "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">" + MyMonth + "</span></p></body></html>",
                                       None))
        self.label_70.setText(_translate("MainWindow",
                                       "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">" + MyMonth + "</span></p></body></html>",
                                       None))
        self.label_80.setText(_translate("MainWindow",
                                       "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">" + MyMonth + "</span></p></body></html>",
                                       None))
        self.label_7.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">" + MyAm_Pm + "</span></p></body></html>",
                                      None))
        self.label_57.setText(_translate("MainWindow",
                                       "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">" + MyAm_Pm + "</span></p></body></html>",
                                       None))
        self.label_67.setText(_translate("MainWindow",
                                       "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">" + MyAm_Pm + "</span></p></body></html>",
                                       None))
        self.label_77.setText(_translate("MainWindow",
                                       "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">" + MyAm_Pm + "</span></p></body></html>",
                                       None))

class FaderWidget(QWidget):
    def __init__(self, old_widget, new_widget):
        QtGui.QWidget.__init__(self, new_widget)

        self.old_pixmap = QPixmap(new_widget.size())
        old_widget.render(self.old_pixmap)
        self.pixmap_opacity = 0.99

        self.timeline = QTimeLine()
        self.timeline.valueChanged.connect(self.animate)
        self.timeline.finished.connect(self.close)
        self.timeline.setDuration(333)
        self.timeline.start()

        self.resize(new_widget.size())
        self.show()

    def paintEvent(self, event):
        painter = QPainter()
        painter.begin(self)
        painter.setOpacity(self.pixmap_opacity)
        painter.drawPixmap(0, 0, self.old_pixmap)
        painter.end()

    def animate(self, value):
        self.pixmap_opacity = (1.0 - value)
        self.repaint()


class StackedWidget(QStackedWidget):
    def __init__(self, parent=None):
        QStackedWidget.__init__(self, parent)

    def setCurrentIndex(self, index):
        self.fader_widget = FaderWidget(self.currentWidget(), self.widget(index))
        QStackedWidget.setCurrentIndex(self, index)